### ISSUE TITLE
how to match image 

### ISSUE THREAD

**Issue by Rainyfish** [sadimanna/computer_vision#1]
when you have finished harris-laplace ,how to match image with those corner features.In other words ,how do you use the information of harris-laplace corners .If change them to descriptors ,but how ? can you teach me how to do that? Or do you have some paper of this methods ?

**Comment by sadimanna** [comment]
Well, what I did in this code is implementing the **Bag-of-Words** method and to extract the features I used HoG features of the interest points.
Actually, The script **visual_words.m** calls the **harris_affine** function which calls the **harris_laplace** function to detect the scale invariant interest points as initialization points.
 
Now, after the interest points are detected, 
1. I extract the HoG features at the interest points.
2. Then Cluster them to create **visual words**.
3. Then, I use these **visual words** to create a **bag-of-words** representation of the object.
Call it a **document** of the **visual words**.

This can be done for various objects, like cats,dogs,horse,cow,etc.

Thus there will be several sets of visual words for several objects.
For example, for cats we get a set of visual words which can be treated as a document of visual words for cats.
Again for dogs we get a set of visual words which can be treated as a document of visual words for dogs.

4. Now, in the **testing phase** the same procedure is followed till the extraction of features or visual words.

5. Now, you can check the document of visual words with which the image under test has the most similarity or has more visual words in common.
For this step, you can train a classifier with the previously obtained visual words for each object.

This is the method I used.

Let me know, if this helps. :)

**Comment by Rainyfish** [comment]
Thanks , I  understand what you mean . First,find the interest patches,and then extract some descriptors in those patches,like HoG features or SIFT features. Finally ,treat those descriptors as words ,cluster and use BoW model  as the final features. Is those steps above right?

**Comment by sadimanna** [comment]
Yes, you are right.

1. Extract the features
2. Cluster them
3. Use the clustered results, i.e. the centres, as **visual words**

Let me know if you get the desired results :)

**Comment by Rainyfish** [comment]
the function harris_affine has no outputs,and It appears that the indicated function return value is never set

**Comment by sadimanna** [comment]
Sorry for your inconvenience.
I uploaded the unfinished draft of the code.
I have now uploaded the completed code.

Though there are some issues with the code that I faced.
The code gave me results in negative which are not desirable at all.
That shouldn't happen because in every loop I check if the co-ordinate value is greater than 2 because I took  a window of 5x5.
So, even if the transformation matrix gives negative results hat should have been discarded in the next loop. But that doesn't happen. I have tested my code multiple times but logical statements doesn't work. 

So I had to extracted the positive results separately as you can see in the last few lines of the code.

I also tried rejecting duplicate points but the function **ismember** somehow doesn't seem to work on my laptop.

But the results after these steps of processing, are **reliable**.


Hope you don't face the problem.
I would request, if the code works fine on your machine, i.e. if you don't get the above mentioned issues give me feedback so that I can check what the error is occurring in my case.

Let me know, if you have any further issues regarding this one.

**Comment by sadimanna** [comment]
Lett me know, if the code gives you the desired results :)
