### ISSUE TITLE
can't run this program on my computer

### ISSUE THREAD

**Issue by helcpp** [sadimanna/computer_vision#2]
I'm a beginner in matlab. I can't run this program on my computer.
Could you tell me the matlab vision, and system operator in your computer .
Your codes helped me a lot. Thanks. :)

**Comment by sadimanna** [comment]
@Hello-X , I am really happy to hear that my code is of help to you.

I think the problem is not with your version of **Matlab** or **System Operator**.

I didn't do the code in **Matlab**. I did in **Octave**.

**Matlab** and **Octave** are almost similar except a few things.

I can suggest you some changes to the code.

1. Change **endwhile** , **endfor** , **endif**, **endfunction** to only **end**
since in Matlab only **end** is used.

2. Change "**~**" i.e. negation sign to "**!**" .
For Example change "**~**=" to "**!**=" 

I also have a version of this code modified for **Matlab**. I mean, all the changes that I suggested has been already done in this code. 
You can also download the code from [here](https://in.mathworks.com/matlabcentral/fileexchange/64365-harris-affine-and-harris-laplace-interest-point-detector). 

Let me know if further problem occurs. :)
Also let me know if the code works perfectly for you. :) :)

**Comment by helcpp** [comment]
I found few problems on my computer. 

(1) The last line of the file "windownormalize.m". On my computer the result only 1 or 0.  
(2) At the beginning of each iteration, I think we should make affine to the image use Ux, and then get the neighborhood of feature points.

This above is my personal understanding.  
Thanks for your information and for being so helpful. :)

**Comment by sadimanna** [comment]
Well, what you said about windownormalize.m , I guess that shouldn't happen. 
And I didn't understand what you meant by "make affine to the image"

**Comment by sadimanna** [comment]
At the beginning of the loop

First, what I am doing is xk = inv(Uk)*xk
Then, I am taking the neighbourhood of the point.

That's what should be done right?
Then, what is the problem you are having?
Can you please elaborate?

**Comment by sadimanna** [comment]
If there is any correction to be done, please tell me.

**Comment by sadimanna** [comment]
![window](https://user-images.githubusercontent.com/21175586/30783069-0011b4c2-a15b-11e7-939c-8946a3389d66.png)


On my computer, calling windownormalize.m gives this result

**Comment by helcpp** [comment]
On my computer, I used python to write the program. I always have the same result in each iteration, it not change any more . My program  has a lot of problems. and could not get the correct result.

 xk = inv(Uk)*xk just a point in the image. Actually the neighbourhood of xk also changed.  The surrounding point is not the original point.  
 
 I do not know if my understanding is right.

**Comment by sadimanna** [comment]
xk = inv(Uk)*xk 

That's what we are supposed to do. Right?

quoting directly from wikipedia:
At every kth iteration, each interest region is defined by several parameters that the algorithm must discover: the Uk matrix, position xk, integration scale sigma_I and differentiation scale sigma_D. Because the detector computes the second-moment matrix in the transformed domain, it's convenient to denote this transformed position as x_w_k where Uk*x_w_k = x_k

**Comment by sadimanna** [comment]
x_k is the position in the original image domain
x_w_k is the position in the transformed image domain.
and the relation between them is x_w_k = inv(U_k)*x_k

Doing x_w_k = inv(U_k)*x_k we get the U-normalized point

So are you saying that we have to apply the above equation to the whole neighbourhood of x_k?

**Comment by sadimanna** [comment]
I think, you are right. We have to transform the whole neighbourhood.

Thank you very much for pointing out this flaw.

**Comment by helcpp** [comment]
I think, we have to apply the equation to the whole image. and then get the neighbourhood in the new image.

**Comment by sadimanna** [comment]
![result](https://user-images.githubusercontent.com/21175586/30783659-5d8b858e-a164-11e7-9db8-e90f87ac2625.png)


This is the result of running my code

green square is the affine invariant points : 3
blue square is the scale invariant points : 340

**Comment by helcpp** [comment]
Great job!

**Comment by sadimanna** [comment]
If we apply the transformation to the whole Image, then what if the co-ordinates in the transformed image we get is greater than the image dimensions?

I am saying this, because I have obtained points which are greater than the image dimensions and even negative values, so there are chances where we can get these problems.

**Comment by sadimanna** [comment]
Okay, I will modify my code and try transforming the whole Image. I will get back to you soon.

I think you may be right. Because in this Image there should more than 3 Affine Invariant Points.
Anyway I will get back to you soon with results.

Thanks for your feedback.

**Comment by helcpp** [comment]
I am waiting for your good news. :)

**Comment by sadimanna** [comment]
![algo](https://user-images.githubusercontent.com/21175586/30784279-0340d1cc-a170-11e7-8cdc-20cdfa216a01.png)


This is confusing me with the thing you said.

For more clear discussion, may I suggest contacting me on FB if you don't mind. I am on FB with the same name on my profile.

**Comment by sadimanna** [comment]
So, I studied the paper once again and I think they are also saying about transforming the point only.

And another thing is I found a bug in my code. I will try to correct it asap. Sorry for the inconvenience I caused you.

Please look into the figure I have given above and communicate with me.
It's been very helpful to me talking to you. :)
